// Generated by CoffeeScript 1.6.3
(function() {
  var RectangleTool, ToolControls, TranscriptionControls, TranscriptionTool, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _ref = (typeof window !== "undefined" && window !== null ? window.MarkingSurface : void 0) || require('marking-surface'), ToolControls = _ref.ToolControls, RectangleTool = _ref.RectangleTool;

  TranscriptionControls = (function(_super) {
    __extends(TranscriptionControls, _super);

    TranscriptionControls.prototype.template = '<textarea style="height: 3em; width: 100%"></textarea>';

    function TranscriptionControls() {
      TranscriptionControls.__super__.constructor.apply(this, arguments);
      this.textarea = this.el.querySelector('textarea');
      this.addEvent('input', 'textarea', this.onChangeTextarea);
    }

    TranscriptionControls.prototype.onChangeTextarea = function(e) {
      return this.tool.mark.set('content', this.textarea.value);
    };

    TranscriptionControls.prototype.onToolSelect = function() {
      TranscriptionControls.__super__.onToolSelect.apply(this, arguments);
      return this.textarea.style.display = '';
    };

    TranscriptionControls.prototype.onToolDeselect = function() {
      TranscriptionControls.__super__.onToolDeselect.apply(this, arguments);
      return this.textarea.style.display = 'none';
    };

    TranscriptionControls.prototype.render = function() {
      TranscriptionControls.__super__.render.apply(this, arguments);
      return this.el.style.width = "" + (this.tool.outline.el.getBoundingClientRect().width) + "px";
    };

    return TranscriptionControls;

  })(ToolControls);

  TranscriptionTool = (function(_super) {
    __extends(TranscriptionTool, _super);

    TranscriptionTool.Controls = TranscriptionControls;

    function TranscriptionTool() {
      TranscriptionTool.__super__.constructor.apply(this, arguments);
      this.mark.content = '';
    }

    TranscriptionTool.prototype.onInitialRelease = function() {
      var _ref1;
      TranscriptionTool.__super__.onInitialRelease.apply(this, arguments);
      return (_ref1 = this.controls) != null ? _ref1.textarea.focus() : void 0;
    };

    TranscriptionTool.prototype.render = function() {
      var _ref1;
      TranscriptionTool.__super__.render.apply(this, arguments);
      return (_ref1 = this.controls) != null ? _ref1.moveTo({
        x: this.mark.left,
        y: this.mark.top + this.mark.height
      }) : void 0;
    };

    return TranscriptionTool;

  })(RectangleTool);

  if (typeof window !== "undefined" && window !== null) {
    window.MarkingSurface.TranscriptionTool = TranscriptionTool;
  }

  if (typeof module !== "undefined" && module !== null) {
    module.exports = TranscriptionTool;
  }

}).call(this);
